
### Find event by id
GET http://localhost:3000/api/events/1


### Find all events by userId
GET http://localhost:3000/api/events?createdBy=11	

### Remove event by id
DELETE http://localhost:3000/api/events/1


### add event
POST http://localhost:3000/api/events/
Content-Type: application/json

{
  "title": "Senior devops dsadwadsadsa sasdsdaad ssdsad",
  "description": "TU BEDZIE MEGA DLUGI TEKTS Z TEXT EDITORA W HTMLU ZAPEWNE",
  "contract": "Full-time",
  "location": "Remote",
  "country": "DLIUUUGUGUUGUGUGUGUGUGUUG",
  "company": "NONODASDAW"
}


### update event
PATCH http://localhost:3000/api/events/4
Content-Type: application/json

{
  "title": "Senior devops v2",
  "description": "UPDATE",
  "contract": "UPD Full-time",
  "location": "UPD Remote"
}